@base = http://localhost:3000
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxODk2MzM3MTM1MTgzMmM2MzA1ZGRkMiIsImVtYWlsIjoiYW5hQGdtYWlsLmNvbSIsImlhdCI6MTYzNjU2NTIyNiwiZXhwIjoxNjM2NTY1MjI2fQ.7ymZajs219Np6y02tKEiBrKqzIk10Pm6E4O1Rfalh6Y



### Obter todos os usuários
GET {{base}}/users
Authorization: {{token}}


### Obter um usuário pelo ID
GET {{base}}/users/6182d2d4c92ef39ba402dbdd
Authorization: {{token}}

### Criar usuário
POST {{base}}/users
Content-Type: application/json

{
  "name": "Ana Flávia Ferreira",
  "email": "ana@gmail.com",
  "password": "1234"
}


### Atualizar usuário
PUT {{base}}/users
Content-Type: application/json
Authorization: {{token}}

{
  "id": "6182d2d4c92ef39ba402dbdd",
  "name": "Diana Marcondes",
  "email": "diana@gmail.com",
  "password": "1234"
}


### Deletar um usuário
DELETE {{base}}/users/6182d2e0c92ef39ba402dbdf
Authorization: {{token}}